### ISSUE TITLE
Locale image insert popup

### ISSUE THREAD

**Issue by joshephan** [syncfusion/ej2-vue-ui-components#45] opened 2020-06-07 14:07 UTC
![제목 없음](https://user-images.githubusercontent.com/4365470/83970959-893a6600-a913-11ea-96aa-e0882a167819.jpg)

How to change this popup language change?

**Comment by Indrajith-Sync** [comment] 2020-06-08 12:15
Hi @joshephan ,

Greetings from Syncfusion support,

We have validated your reported query. Yes, you can apply locale to the insertImage Dialog using the L10 class and load translation object in your application. We have also prepared a sample that tries to meet your requirements. In the below sample, we have loaded locale for “de-DE”, you can also load the desired locale text corresponding to the Rich Text Editor properties.

Sample : https://codesandbox.io/s/vue-template-o6rvv

Please let us know if the solution helps,

Regards,
Indrajith

**Comment by joshephan** [comment] 2020-06-10 07:47
Thank you for your answer.

It doesn't work in my Nuxt environment, should I put L10n in a separate plugins? Now I've been using the editor in plugins this way.

`
// ~/plugins/editor.js 
import Vue from "vue";
import { RichTextEditorPlugin } from "@syncfusion/ej2-vue-richtexteditor";
Vue.use(RichTextEditorPlugin);
`

And I tried like this.

`
// ~/plugins/editor.js 

import Vue from "vue";
import { RichTextEditorPlugin } from "@syncfusion/ej2-vue-richtexteditor";
import { L10n } from "@syncfusion/ej2-base";

L10n.load({
  "ko-KR": {
    "richtexteditor": {
      dialogInsert: "추가하기",
      dialogCancel: "취소",
      dialogUpdate: "업로드",
      imageHeader: "이미지/영상 업로드",
      imageLinkHeader: "또는 링크 주소를 입력해 파일을 업로드할 수 있습니다.",
      imageUploadMessage: "10MB 이하의 이미지 또는 영상 파일을 업로드해주세요.",
      browse: "선택",
      imageUrl: "URL",
      linkTitle: "링크 입력",
      imageCaption: "캡션",
      imageSizeHeader: "이미지 사이즈",
      imageHeight: "높이",
      imageWidth: "너비"
    }
  }
});
Vue.use(RichTextEditorPlugin);
`

But this is not working and also I tried add import code on editor.vue file but not working.

**Comment by Indrajith-Sync** [comment] 2020-06-15 03:12
Hi @joshephan ,

Have you mapped the locale property with the Rich Text Editor Locale property? 

`<ejs-richtexteditor id="default" ref="rteInstance" **locale="de-DE"**>
      <p>Syncfusion RichTextEditor</p>
  </ejs-richtexteditor>`

Regards,
Indrajith

**Comment by rajendranr-5483** [comment] 2020-07-21 17:16
Hi @joshephan ,

Have you checked the proposed solution? we are closing this thread now. Reopen it if you have any queries.

**Comment by bhavesh-786** [comment] 2020-07-21 17:46
I am also having same issue and it's not working. @Indrajith-Sync  It's mapped into this example or some other way to do please suggest me how to do 
Please check this https://codesandbox.io/s/vue-template-o6rvv?file=/src/App.vue

**Comment by Indrajith-Sync** [comment] 2020-07-22 12:55
Hi @bhavesh-786 ,

Greetings from Syncfusion support,

We have checked the sample and able to reproduce the reported issue. The locale object is not loaded properly in the codesandbox sample, hence the locale is not applied. We have also prepared a sample that tries to meet your requirements.

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/RichTextEditor_locale-831380141 

Documentation: https://ej2.syncfusion.com/vue/documentation/rich-text-editor/globalization/

Regards,
Indrajith

**Comment by bhavesh-786** [comment] 2020-07-22 15:10
Thank You for responce @Indrajith-Sync 
In example I am using L10n and loading this language and I have added into ejs-richtexteditor locale also but still it;s not affection. as like I have given into example. what's wrong with this example could you please suggest me with these above example. Because I have tried to follow document also but didn't affected.

**Comment by bhavesh-786** [comment] 2020-07-23 07:31
Hello @Indrajith-Sync 
I have tried this documentation also but it;s not working at all with my code. I have created same like codesandbox and I have followed document as well but nothing affected.

I am working for multi language and I am stuck fully.

Please help me on this topic.
Thank You

**Comment by Indrajith-Sync** [comment] 2020-10-07 08:40
Hi @bhavesh-786 ,

As we said earlier, the locale object is not loaded properly in the codesandbox sample, hence the locale is not applied. We have also prepared a sample that tries to meet your requirements using the L10n load, which works fine.

Sample: https://www.syncfusion.com/downloads/support/directtrac/general/ze/RichTextEditor_locale-831380141

Can you please check the above sample and let us know if it meets your requirements ?

Regards,
Indrajith

**Comment by ajithr** [comment] 2020-12-18 04:53
We are closing this issue since there is no recent activity. Feel free to reopen the issue and update your comments for the reinvestigation.

**Closed by ajithr** 2020-12-18 04:53 UTC
Labels: dialog
