### ISSUE TITLE
ej2-grids excel export exception

### ISSUE THREAD

**Issue by waiyanmintun** [syncfusion/ej2-vue-ui-components#64] opened 2021-04-01 04:35 UTC
Uncaught (in promise) TypeError: Cannot read property 'textContent' of undefined
    at ExcelExport.getAggreateValue (excel-export.js?6e1f:771)
    at ExcelExport.fillAggregates (excel-export.js?6e1f:657)
    at ExcelExport.processAggregates (excel-export.js?6e1f:629)
    at ExcelExport.processRecordContent (excel-export.js?6e1f:379)
    at ExcelExport.processGridExport (excel-export.js?6e1f:353)
    at eval (excel-export.js?6e1f:232)
    at new Promise (<anonymous>)
    at ExcelExport.processInnerRecords (excel-export.js?6e1f:230)
    at eval (excel-export.js?6e1f:136)

"@syncfusion/ej2-vue-grids": "^19.1.54"

//changing @syncfusion/ej2-grids/src/grid/actions/excel-export.js
if (txt.length === 0) {
 return null
}
fix the issue.

**Comment by rajapandiyan-settu** [comment] 2021-04-09 12:22
Hi,

Greetings from Syncfusion support.

We are tried to reproduce the reported behavior, but it was unsuccessful at our end. Excel exporting in EJ2 Grid is working fine with the aggregates. Please find the below sample for your reference.

Sample: https://codesandbox.io/s/vue-forked-gd9db?file=/src/App.vue

Please share the below details to reproduce the reported behavior at our end.

1.	Share the full Grid code you have used.
2.	Share the package.json file with us.
3.	Did you facing the issue in latest version only or previous version too?
4.	If possible, share a simple issue reproducible sample or try to reproduce the issue in given sample. 

Regards,
Rajapandiyan S

**Comment by waiyanmintun** [comment] 2021-04-16 10:31
Dear Syncfusion Team,
Thank you for your reply.
I've reproduced issue at following repo
https://codesandbox.io/s/vue-forked-bqihw?file=/src/App.vue

Regards,
Wai Yan

**Comment by farveensulthana** [comment] 2021-12-23 15:06
Hi Wai Yan,

We are able to replicate the problem while using Aggregates. We will validate your problem with high Priority and update you further details by 27th December 2021. Until then we appreciate your patience.

Regards,
Farveen sulthana T

**Comment by farveensulthana** [comment] 2022-01-10 14:11
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/FARVEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<link rel=themeData
href="file:///C:/Users/FARVEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/FARVEE~1/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;
word-wrap:break-word'>


<p class=MsoNormal>Hi Wai Yan,<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p class=MsoNormal>We apologized for the delayed response.<o:p></o:p></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

<p style='margin:0in'>Further analyzing, we have confirmed it as a bug and
logged the defect report for the same “<b>Exporting with Aggregates throws
script Error”</b>. Thank you for taking the time to report this issue and
helping us improve our product. At Syncfusion, we are committed to fixing all
validated defects (subject to technical feasibility and Product Development
Life Cycle ) and the issue fix will be included in the weekly patch release
scheduled on<b> 1<sup>st</sup> February 2022</b>. Until then we appreciate your
patience.<o:p></o:p></p>

<p style='margin:0in'><br>
You can now track the current status of your request, review the proposed
resolution timeline, and contact us for any further inquiries through this link.<br>
<a
href="https://www.syncfusion.com/feedback/31771/exporting-with-aggregates-throws-script-error-in-vue">https://www.syncfusion.com/feedback/31771/exporting-with-aggregates-throws-script-error-in-vue</a><o:p></o:p></p>

<p style='margin:0in'><o:p>&nbsp;</o:p></p>

<p class=MsoNormal style='background:white'><b><i><span style='color:black'>Disclaimer:</span></i></b><i><span
style='color:black'> The feedback link is in review state and you can view it
once it is validated.<o:p></o:p></span></i></p>

<p class=MsoNormal style='background:white'><i><o:p>&nbsp;</o:p></i></p>

<p class=MsoNormal style='background:white'><i><span style='color:black'>Until
this we suggest to use this workaround solution to resolve the problem. Refer
to the code below:-</span><o:p></o:p></i></p>

<p class=MsoNormal style='background:white'><i><o:p>&nbsp;</o:p></i></p>



toolbarClick: function(args)         {             var treegrid   = document.getElementsByClassName("e-treegrid")[0].ej2_instances;             treegrid[0].grid.isVue =   true;             if   (args.item.text === "Excel   Export")             {                 // 'Grid_excelexport' -> Grid component   id + _ + toolbar item name                 this.$refs.grid.excelExport();             }       },
--




<p class=MsoNormal style='background:white'><i><o:p>&nbsp;</o:p></i></p>

<p class=MsoNormal style='background:white'><b><span style='color:black'>Modified
sample Link</span></b><i><span style='color:black'>:- <a
href="https://codesandbox.io/s/vue-forked-gwy5q?file=/src/App.vue:3900-4239">https://codesandbox.io/s/vue-forked-gwy5q?file=/src/App.vue:3900-4239</a></span><o:p></o:p></i></p>

<p class=MsoNormal style='background:white'><i><o:p>&nbsp;</o:p></i></p>

<p class=MsoNormal style='background:white'><span style='color:black'>Please
get back to us if you need any further assistance.</span><o:p></o:p></p>

<p style='margin:0in'><o:p>&nbsp;</o:p></p>

<p style='margin:0in'>Regards,<o:p></o:p></p>

<p style='margin:0in'>Farveen sulthana T<o:p></o:p></p>


</body>

</html>

**Comment by syncsiva** [comment] 2022-02-09 13:20
Closing the issue since no activity for past 20 days.

**Closed by syncsiva** 2022-02-09 13:20 UTC
Labels: data-grid, tree-grid
