### ISSUE TITLE
Grid: persistSelection not working on grid refresh when allowSelection is binded to a component property

### ISSUE THREAD

**Issue by maidmehic** [syncfusion/ej2-vue-ui-components#74] opened 2021-09-20 08:08 UTC
Hi,
When binding to `allowSelection` property, grid is deselecting the lastly selected row on grid refresh. Expected behavior would be to persist all the previous selected rows because the `persistSelection` is set to `true`.

Grid component:
` <ejs-grid
      ref="grid"
      :dataSource="dataSource"
      :columns="columns"
      :allowSelection="allowSelection"
      :selectionSettings="selectionSettings"
/>`

selectionSettings:
`const selectionSettings = ref({
        type: "Multiple",
        enableSimpleMultiRowSelection: true,
        persistSelection: true,
        checkboxOnly: true,
})`

If `allowSelection` is untouched (default - always `true`), everything is working as expected.

**Comment by Ajithbala** [comment] 2021-10-04 04:16
Hi Customer, 

Thanks for contacting Syncfusion support. 

Query: When binding to `allowSelection` property, grid is deselecting the lastly selected row on grid refresh. Expected behavior would be to persist all the previous selected rows because the `persistSelection` is set to `true`. Grid component: ` ` selectionSettings: `const selectionSettings = ref({ type: "Multiple", enableSimpleMultiRowSelection: true, persistSelection: true, checkboxOnly: true, })` 
 
Based on your query, you are facing row deselecting issue when refresh the Grid component with persistSelection. So, we have prepared sample with persistSelection and found the selected rows are persisted properly after refreshing the Grid component. For your convenience we have attached the sample, please refer them for your reference. 

Code Example: 
` <button v-on:click="onClick">Grid Refresh</button> 
    <ejs-grid 
      ref="grid" 
      :dataSource="data" 
      allowPaging="true" 
      :pageSettings="pageSettings" 
      :selectionSettings="selectionSettings" 
      allowSelection="true" 
    >….. 
</ejs-grid> 

export default Vue.extend({ 
  data: () => { 
    return { 
      data: gridData, 
      pageSettings: { pageSize: 5 }, 
      editSettings: { 
        allowEditing: true, 
        allowAdding: true, 
        allowDeleting: true, 
        mode: "Dialog", 
      }, 

      selectionSettings: { 
        persistSelection: true, 
        checkboxOnly: true, 
        type: "Multiple", 
        enableSimpleMultiRowSelection: true, 
      }, 
    }; 
  }, 
  methods: { 
    onClick: function (e) { 
      this.$refs.grid.refresh(); 
    }, 
  }, 
`

Sample Link: https://codesandbox.io/s/vue-template-forked-xjb02?file=/src/App.vue 

If you still face the issue, then please share the below details to find the root cause of the issue. 

Share the complete Grid code example.

If possible, please share the issue reproducible sample.
 
Share the video demonstration of the reported issue.
 
Share the Syncfusion package version.
 
Regards, 
Ajith G.

**Comment by Pavithra15** [comment] 2022-03-03 08:43
Hi @maidmehic,

We already have logged a defect report “**Persist Selection is not working properly after enabling selection dynamically**” and the fix has been included in our patch release (v19.3.54). So please update your packages to the latest version to overcome the issue.

Release Notes: [https://ej2.syncfusion.com/vue/documentation/release-notes/19.3.54/?type=all#grid](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fej2.syncfusion.com%2Fvue%2Fdocumentation%2Frelease-notes%2F19.3.54%2F%3Ftype%3Dall%23grid&data=04%7C01%7Cpavithra.subramaniyam%40syncfusion.com%7C3338d7e3882844e3a54c08d9fcdbfce0%7C77f1fe12b04949198c509fb41e5bb63b%7C0%7C0%7C637818844044901012%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=wy%2FO22cux9tppE6hF8uK%2FIqnNRqx5WuVr0KC7708W%2Fc%3D&reserved=0)

Regards,
Pavithra S

**Closed** 2022-03-04 04:18 UTC
Labels: data-grid
